version: "3.9"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run dev

  identity-service:
    build:
      context: ./identity-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./identity-service:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run dev

  student-service:
    build:
      context: ./student-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./student-service:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run dev

  course-service:
    build:
      context: ./course-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./course-service:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run dev

  grade-service:
    build:
      context: ./grade-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./grade-service:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run dev

  # media-service:
  #   build:
  #     context: ./media-service
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./media-service:/usr/src/app
  #     - /usr/src/app/node_modules
  #   command: pnpm run dev

  # search-service:
  #   build:
  #     context: ./search-service
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./search-service:/usr/src/app
  #     - /usr/src/app/node_modules
  #   command: pnpm run dev

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile.dev
    volumes: 
      - ./notification-service:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run dev
    
